apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: mjumbe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          command:
            - "redis-server"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          readinessProbe:
             tcpSocket:
               port: 6379
             initialDelaySeconds: 5
             periodSeconds: 10
          livenessProbe:
             tcpSocket:
               port: 6379
             initialDelaySeconds: 15
             periodSeconds: 20
