name: Build and Release JAR

on:
  push:
    paths:
      - "src/**"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build with Maven
        run: mvn clean package

      # Create the target directory for the JAR
      - name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/build/artifacts

      # Move the JAR file to the specified path
      - name: Move JAR to artifacts directory
        run: mv target/*.jar ${{ github.workspace }}/build/artifacts/app.jar

      - uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: Package
          path: ${{ github.workspace }}/build/artifacts/app.jar
          overwrite: true
